# Generated by Django 4.2.5 on 2023-10-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Election_name', models.CharField(max_length=25)),
                ('Election_date', models.DateField()),
                ('status', models.CharField(choices=[('o', 'Open'), ('d', 'Done')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('voter_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=2)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=2)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('elect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.election')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.position')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.candidate')),
                ('elec_tion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.voter')),
            ],
        ),
    ]
